name: Dependabot Updates for Dockerfiles
description: Generates Dependabot update entries for Dockerfiles.
runs:
  using: node16
  main: dist/main.js
branding:
  icon: file-plus
  color: blue
inputs:
  interval:
    description: TODO
    default: weekly
